name: .net core Deployment

on: [push]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-1
          context: ./sidstar-backend/sidstar-backend

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sid_backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd sidstar-backend
          cd sidstar-backend
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
           # Push the new image ID in the Amazon ECS task definition
          echo "${{ steps.build-image.outputs.image }}"

      - name: Push the new image ID in the Amazon ECS task definition
        id: sid-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./sidstar-backend/sidstar-backend/task-definition.json
          container-name: sid-container
          image: ${{ steps.build-image.outputs.image }}

      # Deploy Amazon ECS task definition
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.sid-task.outputs.task-definition }}
          service: sid-services
          cluster: Sid-cluster
          wait-for-service-stability: true
