name: VueFrontend

on: [push]

jobs:
  run-vuejs-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Npm install & npm build
        run: |
          npm install
          npm run build
